# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import texteditor_pb2 as texteditor__pb2


class TextEditorStub(object):
    """python -m grpc_tools.protoc --proto_path=./protos --python_out=. --grpc_python_out=. texteditor.proto

    Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveToServer = channel.unary_unary(
                '/chat.TextEditor/SaveToServer',
                request_serializer=texteditor__pb2.Download.SerializeToString,
                response_deserializer=texteditor__pb2.FileResponse.FromString,
                )
        self.DeleteFromServer = channel.unary_unary(
                '/chat.TextEditor/DeleteFromServer',
                request_serializer=texteditor__pb2.FileResponse.SerializeToString,
                response_deserializer=texteditor__pb2.FileResponse.FromString,
                )
        self.BackupEdits = channel.unary_stream(
                '/chat.TextEditor/BackupEdits',
                request_serializer=texteditor__pb2.KeepAliveRequest.SerializeToString,
                response_deserializer=texteditor__pb2.Download.FromString,
                )
        self.OpenNewFile = channel.unary_unary(
                '/chat.TextEditor/OpenNewFile',
                request_serializer=texteditor__pb2.Download.SerializeToString,
                response_deserializer=texteditor__pb2.FileResponse.FromString,
                )
        self.OpenExistingFile = channel.unary_stream(
                '/chat.TextEditor/OpenExistingFile',
                request_serializer=texteditor__pb2.Download.SerializeToString,
                response_deserializer=texteditor__pb2.Data.FromString,
                )
        self.Heartbeats = channel.stream_stream(
                '/chat.TextEditor/Heartbeats',
                request_serializer=texteditor__pb2.KeepAliveRequest.SerializeToString,
                response_deserializer=texteditor__pb2.KeepAliveResponse.FromString,
                )
        self.Listen = channel.unary_stream(
                '/chat.TextEditor/Listen',
                request_serializer=texteditor__pb2.Username.SerializeToString,
                response_deserializer=texteditor__pb2.Download.FromString,
                )
        self.ListenForDeletes = channel.unary_stream(
                '/chat.TextEditor/ListenForDeletes',
                request_serializer=texteditor__pb2.Username.SerializeToString,
                response_deserializer=texteditor__pb2.Download.FromString,
                )
        self.SignInExisting = channel.unary_unary(
                '/chat.TextEditor/SignInExisting',
                request_serializer=texteditor__pb2.Username.SerializeToString,
                response_deserializer=texteditor__pb2.Unreads.FromString,
                )


class TextEditorServicer(object):
    """python -m grpc_tools.protoc --proto_path=./protos --python_out=. --grpc_python_out=. texteditor.proto

    Interface exported by the server.
    """

    def SaveToServer(self, request, context):
        """A simple RPC.

        Saves file from client to primary server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFromServer(self, request, context):
        """Deletes file on primary server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupEdits(self, request, context):
        """Send new edits from primary to backups
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenNewFile(self, request, context):
        """Opens new text file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenExistingFile(self, request, context):
        """Opens existing text file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeats(self, request_iterator, context):
        """Periodic messages from primary server to each backup server to 
        determine if primary server or backup servers have failed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Listen(self, request, context):
        """Response stream for client to receive messages from server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenForDeletes(self, request, context):
        """Response stream for client to delete files from server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignInExisting(self, request, context):
        """Signs in existing user and gets unread messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextEditorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveToServer,
                    request_deserializer=texteditor__pb2.Download.FromString,
                    response_serializer=texteditor__pb2.FileResponse.SerializeToString,
            ),
            'DeleteFromServer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFromServer,
                    request_deserializer=texteditor__pb2.FileResponse.FromString,
                    response_serializer=texteditor__pb2.FileResponse.SerializeToString,
            ),
            'BackupEdits': grpc.unary_stream_rpc_method_handler(
                    servicer.BackupEdits,
                    request_deserializer=texteditor__pb2.KeepAliveRequest.FromString,
                    response_serializer=texteditor__pb2.Download.SerializeToString,
            ),
            'OpenNewFile': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenNewFile,
                    request_deserializer=texteditor__pb2.Download.FromString,
                    response_serializer=texteditor__pb2.FileResponse.SerializeToString,
            ),
            'OpenExistingFile': grpc.unary_stream_rpc_method_handler(
                    servicer.OpenExistingFile,
                    request_deserializer=texteditor__pb2.Download.FromString,
                    response_serializer=texteditor__pb2.Data.SerializeToString,
            ),
            'Heartbeats': grpc.stream_stream_rpc_method_handler(
                    servicer.Heartbeats,
                    request_deserializer=texteditor__pb2.KeepAliveRequest.FromString,
                    response_serializer=texteditor__pb2.KeepAliveResponse.SerializeToString,
            ),
            'Listen': grpc.unary_stream_rpc_method_handler(
                    servicer.Listen,
                    request_deserializer=texteditor__pb2.Username.FromString,
                    response_serializer=texteditor__pb2.Download.SerializeToString,
            ),
            'ListenForDeletes': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenForDeletes,
                    request_deserializer=texteditor__pb2.Username.FromString,
                    response_serializer=texteditor__pb2.Download.SerializeToString,
            ),
            'SignInExisting': grpc.unary_unary_rpc_method_handler(
                    servicer.SignInExisting,
                    request_deserializer=texteditor__pb2.Username.FromString,
                    response_serializer=texteditor__pb2.Unreads.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.TextEditor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextEditor(object):
    """python -m grpc_tools.protoc --proto_path=./protos --python_out=. --grpc_python_out=. texteditor.proto

    Interface exported by the server.
    """

    @staticmethod
    def SaveToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.TextEditor/SaveToServer',
            texteditor__pb2.Download.SerializeToString,
            texteditor__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFromServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.TextEditor/DeleteFromServer',
            texteditor__pb2.FileResponse.SerializeToString,
            texteditor__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BackupEdits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.TextEditor/BackupEdits',
            texteditor__pb2.KeepAliveRequest.SerializeToString,
            texteditor__pb2.Download.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenNewFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.TextEditor/OpenNewFile',
            texteditor__pb2.Download.SerializeToString,
            texteditor__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenExistingFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.TextEditor/OpenExistingFile',
            texteditor__pb2.Download.SerializeToString,
            texteditor__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/chat.TextEditor/Heartbeats',
            texteditor__pb2.KeepAliveRequest.SerializeToString,
            texteditor__pb2.KeepAliveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.TextEditor/Listen',
            texteditor__pb2.Username.SerializeToString,
            texteditor__pb2.Download.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenForDeletes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.TextEditor/ListenForDeletes',
            texteditor__pb2.Username.SerializeToString,
            texteditor__pb2.Download.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignInExisting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.TextEditor/SignInExisting',
            texteditor__pb2.Username.SerializeToString,
            texteditor__pb2.Unreads.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
