# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: texteditor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10texteditor.proto\x12\x04\x63hat\"\x18\n\x08Username\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x07Welcome\x12\x12\n\nwelcomeMsg\x18\x01 \x01(\t\"-\n\x07Unreads\x12\x11\n\terrorFlag\x18\x01 \x01(\x08\x12\x0f\n\x07unreads\x18\x02 \x01(\t\".\n\x08\x44ownload\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x03 \x01(\x0c\"3\n\x0c\x46ileResponse\x12\x11\n\terrorFlag\x18\x01 \x01(\x08\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"%\n\x10KeepAliveRequest\x12\x11\n\tbackup_id\x18\x01 \x01(\x05\";\n\x11KeepAliveResponse\x12\x12\n\nprimary_id\x18\x01 \x01(\x05\x12\x12\n\nbackup_ids\x18\x02 \x03(\x05\"\x16\n\x07Payload\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x82\x04\n\nTextEditor\x12\x34\n\x0cSaveToServer\x12\x0e.chat.Download\x1a\x12.chat.FileResponse\"\x00\x12<\n\x10\x44\x65leteFromServer\x12\x12.chat.FileResponse\x1a\x12.chat.FileResponse\"\x00\x12\x39\n\x0b\x42\x61\x63kupEdits\x12\x16.chat.KeepAliveRequest\x1a\x0e.chat.Download\"\x00\x30\x01\x12\x33\n\x0bOpenNewFile\x12\x0e.chat.Download\x1a\x12.chat.FileResponse\"\x00\x12\x32\n\x10OpenExistingFile\x12\x0e.chat.Download\x1a\n.chat.Data\"\x00\x30\x01\x12\x43\n\nHeartbeats\x12\x16.chat.KeepAliveRequest\x1a\x17.chat.KeepAliveResponse\"\x00(\x01\x30\x01\x12,\n\x06Listen\x12\x0e.chat.Username\x1a\x0e.chat.Download\"\x00\x30\x01\x12\x36\n\x10ListenForDeletes\x12\x0e.chat.Username\x1a\x0e.chat.Download\"\x00\x30\x01\x12\x31\n\x0eSignInExisting\x12\x0e.chat.Username\x1a\r.chat.Unreads\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'texteditor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERNAME._serialized_start=26
  _USERNAME._serialized_end=50
  _WELCOME._serialized_start=52
  _WELCOME._serialized_end=81
  _UNREADS._serialized_start=83
  _UNREADS._serialized_end=128
  _DOWNLOAD._serialized_start=130
  _DOWNLOAD._serialized_end=176
  _FILERESPONSE._serialized_start=178
  _FILERESPONSE._serialized_end=229
  _DATA._serialized_start=231
  _DATA._serialized_end=251
  _KEEPALIVEREQUEST._serialized_start=253
  _KEEPALIVEREQUEST._serialized_end=290
  _KEEPALIVERESPONSE._serialized_start=292
  _KEEPALIVERESPONSE._serialized_end=351
  _PAYLOAD._serialized_start=353
  _PAYLOAD._serialized_end=375
  _TEXTEDITOR._serialized_start=378
  _TEXTEDITOR._serialized_end=892
# @@protoc_insertion_point(module_scope)
